let systems = dynamic(
{
    "10.10.0.1/24": 100,
    "10.10.100.0/24": 200,
    "10.10.200.0/24": 200,
    "10.10.300.0/24": 200,
    "10.10.401.0/24": 200
});
pfsense_logstash_CL
| where destination_ip_s !contains '.255'
| mv-expand bagexpansion=array system = systems
| extend cidr = system[0]
| extend threshold = system[1]
| where ipv4_is_match(tostring(destination_ip_s), tostring(cidr))
| summarize amount = count() by source_ip_s, destination_ip_s, tostring(cidr), tostring(threshold)
| sort by amount desc 
| where amount > tolong(threshold)